library(readr)
d <- readRDS("data/exported/d.RDS")
dist_d <- readRDS("data/exported/dist_d.RDS")
DEPT_FTE <- readRDS("data/exported/DEPT_FTE.RDS")
HUM_FTE <- readRDS("data/exported/HUM_FTE.RDS")
joined_noHUM <- readRDS("data/exported/joined_noHUM.RDS")
joined_total <- readRDS("data/exported/joined_total.RDS")
joined_total_units <- readRDS("data/exported/joined_total_units.RDS")
thes_fac <- readRDS("data/exported/thes_fac.RDS")
total_FTE <- readRDS("data/exported/total_FTE.RDS")
total_Units <- readRDS("data/exported/total_Units.RDS")